/* The following code was generated by JFlex 1.4.1 on 10/9/13 6:11 PM */

/*
 * Generated on 10/9/13 6:11 PM
 */
package ide.view;

import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.*;


/**
 * 
 */

public class MarvelTokenMaker extends AbstractJFlexCTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int EOL_COMMENT = 2;
  public static final int YYINITIAL = 0;
  public static final int MLC = 1;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\20\1\10\1\0\1\20\1\16\22\0\1\20\1\35\1\15"+
    "\1\17\1\1\1\35\1\35\1\7\1\37\1\37\1\22\1\25\1\35"+
    "\1\25\1\23\1\21\1\4\3\4\4\6\2\3\1\43\1\35\1\51"+
    "\1\52\1\51\1\35\1\36\6\5\24\1\1\37\1\11\1\37\1\16"+
    "\1\2\1\0\1\31\1\14\1\45\1\46\1\24\1\30\1\50\1\40"+
    "\1\42\2\1\1\32\1\1\1\13\1\47\1\41\1\1\1\27\1\33"+
    "\1\26\1\12\1\1\1\44\3\1\1\34\1\16\1\34\1\35\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\2\1\1\2\1\3\1\4\3\1\1\5\1\6"+
    "\1\7\2\10\7\1\1\11\6\1\1\10\1\12\1\13"+
    "\5\12\1\14\3\12\1\0\1\15\1\0\1\15\1\3"+
    "\1\16\1\0\1\3\3\1\2\5\1\17\1\20\1\21"+
    "\4\1\1\22\10\1\1\23\3\1\1\23\1\24\11\0"+
    "\1\21\1\0\1\3\1\25\2\3\1\16\1\3\3\1"+
    "\1\5\1\26\1\5\11\1\1\27\4\1\11\0\1\3"+
    "\1\1\1\5\1\1\1\30\4\1\2\0\1\31\2\0"+
    "\1\32\1\0\1\3\1\5\1\1\5\0\1\3\1\5";

  private static int [] zzUnpackAction() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\u0102\0\201"+
    "\0\u012d\0\u0158\0\u0183\0\u01ae\0\201\0\u01d9\0\u0204\0\201"+
    "\0\u022f\0\u025a\0\u0285\0\u02b0\0\u02db\0\u0306\0\u0331\0\201"+
    "\0\u035c\0\u0387\0\u03b2\0\u03dd\0\u0408\0\u0433\0\u045e\0\u0489"+
    "\0\201\0\u04b4\0\u04df\0\u050a\0\u0535\0\u0560\0\201\0\u058b"+
    "\0\u05b6\0\u05e1\0\u060c\0\u0637\0\u022f\0\u0662\0\u068d\0\201"+
    "\0\u06b8\0\u06e3\0\u070e\0\u0739\0\u0764\0\u078f\0\u07ba\0\201"+
    "\0\201\0\u07e5\0\u0810\0\u083b\0\u0866\0\u0891\0\254\0\u08bc"+
    "\0\u08e7\0\u0912\0\u093d\0\u0968\0\u0993\0\u09be\0\u09e9\0\u0a14"+
    "\0\u0a3f\0\u0a6a\0\u0a95\0\254\0\201\0\u0ac0\0\u0aeb\0\u0b16"+
    "\0\u0b41\0\u0b6c\0\u0b97\0\u0bc2\0\u0bed\0\u0c18\0\u0c43\0\u0c6e"+
    "\0\u0c99\0\201\0\u0cc4\0\u0cef\0\u06b8\0\u0d1a\0\u0d45\0\u0d70"+
    "\0\u0d9b\0\u0dc6\0\201\0\u0df1\0\u0e1c\0\u0e47\0\u0e72\0\u0e9d"+
    "\0\u0ec8\0\u0ef3\0\u0f1e\0\u0f49\0\u0f74\0\254\0\u0f9f\0\u0fca"+
    "\0\u0ff5\0\u1020\0\u104b\0\u1076\0\u10a1\0\u10cc\0\u10f7\0\u1122"+
    "\0\u114d\0\u1178\0\u11a3\0\u11ce\0\u11f9\0\u1224\0\u124f\0\254"+
    "\0\u127a\0\u12a5\0\u12d0\0\u12fb\0\u1326\0\u1351\0\u137c\0\u13a7"+
    "\0\u13d2\0\u13fd\0\u1428\0\u1453\0\u147e\0\u14a9\0\u14d4\0\u137c"+
    "\0\u14ff\0\u13fd\0\u152a\0\u1555\0\u1580";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\2\6\1\5\1\6\1\7\1\10\1\4"+
    "\1\11\1\12\1\13\1\14\1\4\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\20\1\23\1\24\1\25\1\26"+
    "\1\5\1\27\1\30\2\4\1\30\1\5\1\31\1\32"+
    "\1\4\1\33\1\34\1\35\1\36\1\5\1\37\1\20"+
    "\10\40\1\41\11\40\1\42\5\40\1\43\7\40\1\44"+
    "\3\40\1\45\6\40\10\46\1\47\17\46\1\50\7\46"+
    "\1\51\3\46\1\52\6\46\54\0\6\5\2\0\1\53"+
    "\3\5\7\0\1\5\1\0\6\5\4\0\3\5\1\0"+
    "\5\5\2\0\3\54\2\6\1\54\1\6\2\0\4\54"+
    "\2\0\1\54\3\0\1\55\1\56\1\0\6\54\2\0"+
    "\1\54\1\0\3\54\1\0\5\54\2\0\7\57\1\60"+
    "\1\61\1\62\41\57\1\0\6\5\2\0\1\53\1\5"+
    "\1\63\1\5\7\0\1\5\1\0\6\5\4\0\3\5"+
    "\1\0\5\5\3\0\6\5\2\0\1\53\3\5\7\0"+
    "\1\5\1\0\6\5\4\0\3\5\1\0\3\5\1\64"+
    "\1\5\3\0\6\5\2\0\1\53\3\5\7\0\1\5"+
    "\1\0\6\5\4\0\3\5\1\0\3\5\1\65\1\5"+
    "\2\0\10\14\1\66\1\67\3\14\1\70\35\14\20\0"+
    "\1\16\54\0\1\71\33\0\2\72\1\0\1\72\45\0"+
    "\6\5\2\0\1\53\1\5\1\73\1\5\7\0\1\5"+
    "\1\0\4\5\1\74\1\5\4\0\3\5\1\0\5\5"+
    "\3\0\6\5\2\0\1\53\3\5\7\0\1\5\1\0"+
    "\1\5\1\75\4\5\4\0\1\76\2\5\1\0\3\5"+
    "\1\77\1\5\3\0\6\5\2\0\1\53\3\5\7\0"+
    "\1\100\1\0\6\5\4\0\3\5\1\0\5\5\3\0"+
    "\6\5\2\0\1\53\3\5\7\0\1\5\1\0\3\5"+
    "\1\101\2\5\4\0\3\5\1\0\5\5\3\0\6\5"+
    "\2\0\1\53\1\5\1\102\1\5\7\0\1\5\1\0"+
    "\4\5\1\103\1\5\4\0\3\5\1\0\5\5\3\0"+
    "\6\5\2\0\1\53\3\5\7\0\1\5\1\0\1\104"+
    "\5\5\4\0\3\5\1\0\5\5\3\0\6\5\2\0"+
    "\1\53\1\105\2\5\7\0\1\5\1\0\1\5\1\106"+
    "\4\5\4\0\3\5\1\0\5\5\3\0\6\5\2\0"+
    "\1\53\1\5\1\107\1\5\7\0\1\5\1\0\2\5"+
    "\1\77\2\5\1\110\4\0\3\5\1\0\5\5\3\0"+
    "\6\5\2\0\1\53\3\5\7\0\1\5\1\0\6\5"+
    "\4\0\1\111\2\5\1\0\5\5\3\0\6\5\2\0"+
    "\1\53\3\5\7\0\1\5\1\0\3\5\1\112\2\5"+
    "\4\0\1\113\2\5\1\0\5\5\3\0\6\5\2\0"+
    "\1\53\3\5\7\0\1\5\1\0\6\5\4\0\3\5"+
    "\1\0\3\5\1\77\1\5\3\0\6\5\2\0\1\53"+
    "\3\5\7\0\1\5\1\0\1\5\1\114\4\5\4\0"+
    "\3\5\1\0\5\5\54\0\1\20\10\40\1\0\11\40"+
    "\1\0\5\40\1\0\7\40\1\0\3\40\1\0\6\40"+
    "\21\0\1\115\57\0\1\116\13\0\1\117\36\0\1\120"+
    "\70\0\1\121\6\0\10\46\1\0\17\46\1\0\7\46"+
    "\1\0\3\46\1\0\6\46\26\0\1\122\13\0\1\123"+
    "\36\0\1\124\70\0\1\125\20\0\1\126\40\0\7\54"+
    "\2\0\4\54\2\0\1\54\4\0\1\54\1\0\6\54"+
    "\2\0\1\54\1\0\3\54\1\0\5\54\2\0\3\54"+
    "\2\127\1\54\1\127\2\0\4\54\2\0\1\54\4\0"+
    "\1\54\1\130\6\54\2\0\1\54\1\0\3\54\1\0"+
    "\5\54\2\0\7\131\1\132\1\0\42\131\7\0\1\132"+
    "\43\0\4\131\1\133\1\131\1\134\1\135\1\0\1\57"+
    "\1\136\3\57\10\131\3\57\22\131\1\0\6\5\2\0"+
    "\1\53\3\5\7\0\1\5\1\0\1\137\3\5\1\140"+
    "\1\5\4\0\3\5\1\0\5\5\3\0\6\5\2\0"+
    "\1\53\3\5\7\0\1\5\1\0\1\114\5\5\4\0"+
    "\3\5\1\0\5\5\3\0\6\5\2\0\1\53\3\5"+
    "\7\0\1\5\1\0\6\5\4\0\3\5\1\0\3\5"+
    "\1\141\1\5\2\0\11\66\1\142\3\66\1\143\41\66"+
    "\1\14\1\66\2\14\1\0\1\14\1\144\3\14\10\66"+
    "\3\14\22\66\3\54\2\72\1\54\1\72\2\0\4\54"+
    "\2\0\1\54\4\0\1\56\1\0\6\54\2\0\1\54"+
    "\1\0\3\54\1\0\5\54\3\0\6\5\2\0\1\53"+
    "\3\5\7\0\1\5\1\0\6\5\4\0\3\5\1\0"+
    "\2\5\1\77\2\5\3\0\6\5\2\0\1\53\3\5"+
    "\7\0\1\5\1\0\5\5\1\145\4\0\3\5\1\0"+
    "\5\5\3\0\6\5\2\0\1\53\1\146\2\5\7\0"+
    "\1\5\1\0\6\5\4\0\3\5\1\0\5\5\3\0"+
    "\6\5\2\0\1\53\3\5\7\0\1\147\1\0\6\5"+
    "\4\0\3\5\1\0\5\5\3\0\6\5\2\0\1\53"+
    "\3\5\7\0\1\5\1\0\3\5\1\141\2\5\4\0"+
    "\1\5\1\150\1\5\1\0\5\5\3\0\6\5\2\0"+
    "\1\53\3\5\7\0\1\5\1\0\4\5\1\151\1\5"+
    "\4\0\3\5\1\0\5\5\3\0\6\5\2\0\1\53"+
    "\3\5\7\0\1\5\1\0\6\5\4\0\3\5\1\0"+
    "\2\5\1\114\2\5\3\0\6\5\2\0\1\53\3\5"+
    "\7\0\1\152\1\0\6\5\4\0\3\5\1\0\5\5"+
    "\3\0\6\5\2\0\1\53\3\5\7\0\1\5\1\0"+
    "\1\5\1\153\4\5\4\0\3\5\1\0\5\5\3\0"+
    "\6\5\2\0\1\53\3\5\7\0\1\5\1\0\1\154"+
    "\5\5\4\0\3\5\1\0\5\5\3\0\6\5\2\0"+
    "\1\53\3\5\7\0\1\5\1\0\6\5\4\0\2\5"+
    "\1\155\1\0\5\5\3\0\6\5\2\0\1\53\3\5"+
    "\7\0\1\5\1\0\1\156\5\5\4\0\1\5\1\157"+
    "\1\5\1\0\5\5\3\0\6\5\2\0\1\53\1\5"+
    "\1\12\1\5\7\0\1\5\1\0\6\5\4\0\3\5"+
    "\1\0\5\5\3\0\6\5\2\0\1\53\3\5\7\0"+
    "\1\5\1\0\6\5\4\0\2\5\1\160\1\0\5\5"+
    "\3\0\6\5\2\0\1\53\3\5\7\0\1\5\1\0"+
    "\4\5\1\161\1\5\4\0\3\5\1\0\5\5\3\0"+
    "\6\5\2\0\1\53\3\5\7\0\1\5\1\0\3\5"+
    "\1\162\2\5\4\0\3\5\1\0\5\5\43\0\1\163"+
    "\43\0\1\164\46\0\1\165\70\0\1\166\47\0\1\167"+
    "\43\0\1\170\46\0\1\171\70\0\1\172\11\0\4\173"+
    "\5\0\1\173\7\0\1\173\3\0\2\173\13\0\2\173"+
    "\4\0\3\54\2\127\1\54\1\127\2\0\4\54\2\0"+
    "\1\54\4\0\1\54\1\0\6\54\2\0\1\54\1\0"+
    "\3\54\1\0\5\54\5\0\2\127\1\0\1\127\44\0"+
    "\7\131\1\60\1\0\46\131\1\134\1\131\1\134\1\132"+
    "\1\0\46\131\1\57\1\131\1\57\1\132\1\0\45\131"+
    "\4\174\1\60\1\0\3\131\1\174\7\131\1\174\3\131"+
    "\2\174\13\131\2\174\4\131\1\0\6\5\2\0\1\53"+
    "\3\5\7\0\1\5\1\0\6\5\4\0\2\5\1\161"+
    "\1\0\5\5\3\0\6\5\2\0\1\53\3\5\7\0"+
    "\1\175\1\0\6\5\4\0\3\5\1\0\5\5\3\0"+
    "\6\5\2\0\1\53\3\5\7\0\1\5\1\0\4\5"+
    "\1\156\1\5\4\0\3\5\1\0\5\5\2\0\10\66"+
    "\1\0\45\66\4\176\2\66\1\142\2\66\1\176\1\143"+
    "\6\66\1\176\3\66\2\176\13\66\2\176\4\66\1\0"+
    "\6\5\2\0\1\53\3\5\7\0\1\77\1\0\6\5"+
    "\4\0\2\5\1\177\1\0\5\5\3\0\6\5\2\0"+
    "\1\53\3\5\7\0\1\200\1\0\6\5\4\0\3\5"+
    "\1\0\5\5\3\0\6\5\2\0\1\53\1\5\1\77"+
    "\1\5\7\0\1\5\1\0\6\5\4\0\3\5\1\0"+
    "\5\5\3\0\6\5\2\0\1\53\3\5\7\0\1\201"+
    "\1\0\6\5\4\0\3\5\1\0\5\5\3\0\6\5"+
    "\2\0\1\53\3\5\7\0\1\5\1\0\5\5\1\146"+
    "\4\0\3\5\1\0\5\5\3\0\6\5\2\0\1\53"+
    "\3\5\7\0\1\5\1\0\1\5\1\202\4\5\4\0"+
    "\3\5\1\0\5\5\3\0\6\5\2\0\1\53\3\5"+
    "\7\0\1\5\1\0\6\5\4\0\2\5\1\203\1\0"+
    "\5\5\3\0\6\5\2\0\1\53\3\5\7\0\1\5"+
    "\1\0\5\5\1\77\4\0\3\5\1\0\5\5\3\0"+
    "\6\5\2\0\1\53\1\5\1\202\1\5\7\0\1\5"+
    "\1\0\6\5\4\0\3\5\1\0\5\5\3\0\6\5"+
    "\2\0\1\53\1\202\2\5\7\0\1\5\1\0\6\5"+
    "\4\0\3\5\1\0\5\5\3\0\6\5\2\0\1\53"+
    "\3\5\7\0\1\5\1\0\4\5\1\204\1\5\4\0"+
    "\3\5\1\0\5\5\3\0\6\5\2\0\1\53\3\5"+
    "\7\0\1\5\1\0\4\5\1\77\1\5\4\0\3\5"+
    "\1\0\5\5\3\0\6\5\2\0\1\53\3\5\7\0"+
    "\1\5\1\0\1\5\1\156\4\5\4\0\3\5\1\0"+
    "\5\5\45\0\1\205\33\0\1\163\67\0\1\206\34\0"+
    "\1\207\72\0\1\210\33\0\1\167\67\0\1\211\34\0"+
    "\1\212\32\0\4\213\5\0\1\213\7\0\1\213\3\0"+
    "\2\213\13\0\2\213\4\0\3\131\4\214\1\60\1\0"+
    "\3\131\1\214\7\131\1\214\3\131\2\214\13\131\2\214"+
    "\4\131\1\0\6\5\2\0\1\53\3\5\7\0\1\5"+
    "\1\0\5\5\1\154\4\0\3\5\1\0\5\5\2\0"+
    "\3\66\4\215\2\66\1\142\2\66\1\215\1\143\6\66"+
    "\1\215\3\66\2\215\13\66\2\215\4\66\1\0\6\5"+
    "\2\0\1\53\3\5\7\0\1\5\1\0\2\5\1\77"+
    "\3\5\4\0\3\5\1\0\5\5\3\0\6\5\2\0"+
    "\1\53\3\5\7\0\1\5\1\0\3\5\1\202\2\5"+
    "\4\0\3\5\1\0\5\5\3\0\6\5\2\0\1\53"+
    "\3\5\7\0\1\5\1\0\1\77\5\5\4\0\3\5"+
    "\1\0\5\5\3\0\6\5\2\0\1\53\1\5\1\216"+
    "\1\5\7\0\1\5\1\0\6\5\4\0\3\5\1\0"+
    "\5\5\3\0\6\5\2\0\1\53\3\5\7\0\1\77"+
    "\1\0\6\5\4\0\3\5\1\0\5\5\23\0\1\217"+
    "\64\0\1\163\7\0\1\205\10\0\1\207\1\220\4\207"+
    "\1\220\2\0\3\207\2\0\1\220\1\0\1\207\2\220"+
    "\1\207\1\220\6\207\1\0\3\220\3\207\1\220\5\207"+
    "\1\0\1\220\21\0\1\221\64\0\1\167\7\0\1\210"+
    "\10\0\1\212\1\222\4\212\1\222\2\0\3\212\2\0"+
    "\1\222\1\0\1\212\2\222\1\212\1\222\6\212\1\0"+
    "\3\222\3\212\1\222\5\212\1\0\1\222\3\0\4\223"+
    "\5\0\1\223\7\0\1\223\3\0\2\223\13\0\2\223"+
    "\4\0\3\131\4\224\1\60\1\0\3\131\1\224\7\131"+
    "\1\224\3\131\2\224\13\131\2\224\4\131\3\66\4\225"+
    "\2\66\1\142\2\66\1\225\1\143\6\66\1\225\3\66"+
    "\2\225\13\66\2\225\4\66\1\0\6\5\2\0\1\53"+
    "\3\5\7\0\1\5\1\0\6\5\4\0\3\5\1\0"+
    "\4\5\1\156\23\0\1\207\52\0\1\212\34\0\4\5"+
    "\5\0\1\5\7\0\1\5\3\0\2\5\13\0\2\5"+
    "\4\0\3\131\4\57\1\60\1\0\3\131\1\57\7\131"+
    "\1\57\3\131\2\57\13\131\2\57\4\131\3\66\4\14"+
    "\2\66\1\142\2\66\1\14\1\143\6\66\1\14\3\66"+
    "\2\14\13\66\2\14\4\66";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5547];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\3\1\1\11\4\1\1\11\2\1\1\11"+
    "\7\1\1\11\10\1\1\11\5\1\1\11\3\1\1\0"+
    "\1\1\1\0\2\1\1\11\1\0\6\1\2\11\23\1"+
    "\1\11\11\0\1\1\1\0\1\1\1\11\10\1\1\11"+
    "\17\1\11\0\11\1\2\0\1\1\2\0\1\1\1\0"+
    "\3\1\5\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */


	/**
	 * Constructor.  This must be here because JFlex does not generate a
	 * no-parameter constructor.
	 */
	public MarvelTokenMaker() {
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addToken(int, int, int)
	 */
	private void addHyperlinkToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, true);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int tokenType) {
		addToken(zzStartRead, zzMarkedPos-1, tokenType);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addHyperlinkToken(int, int, int)
	 */
	private void addToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, false);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param array The character array.
	 * @param start The starting offset in the array.
	 * @param end The ending offset in the array.
	 * @param tokenType The token's type.
	 * @param startOffset The offset in the document at which this token
	 *        occurs.
	 * @param hyperlink Whether this token is a hyperlink.
	 */
	public void addToken(char[] array, int start, int end, int tokenType,
						int startOffset, boolean hyperlink) {
		super.addToken(array, start,end, tokenType, startOffset, hyperlink);
		zzStartRead = zzMarkedPos;
	}


	/**
	 * Returns the text to place at the beginning and end of a
	 * line to "comment" it in a this programming language.
	 *
	 * @return The start and end strings to add to a line to "comment"
	 *         it out.
	 */
	public String[] getLineCommentStartAndEnd() {
		return new String[] { "#", null };
	}


	/**
	 * Returns the first token in the linked list of tokens generated
	 * from <code>text</code>.  This method must be implemented by
	 * subclasses so they can correctly implement syntax highlighting.
	 *
	 * @param text The text from which to get tokens.
	 * @param initialTokenType The token type we should start with.
	 * @param startOffset The offset into the document at which
	 *        <code>text</code> starts.
	 * @return The first <code>Token</code> in a linked list representing
	 *         the syntax highlighted text.
	 */
	public Token getTokenList(Segment text, int initialTokenType, int startOffset) {

		resetTokenList();
		this.offsetShift = -text.offset + startOffset;

		// Start off in the proper state.
		int state = Token.NULL;
		switch (initialTokenType) {
						case Token.COMMENT_MULTILINE:
				state = MLC;
				start = text.offset;
				break;

			/* No documentation comments */
			default:
				state = Token.NULL;
		}

		s = text;
		try {
			yyreset(zzReader);
			yybegin(state);
			return yylex();
		} catch (IOException ioe) {
			ioe.printStackTrace();
			return null;
		}

	}


	/**
	 * Refills the input buffer.
	 *
	 * @return      <code>true</code> if EOF was reached, otherwise
	 *              <code>false</code>.
	 */
	private boolean zzRefill() {
		return zzCurrentPos>=s.offset+s.count;
	}


	/**
	 * Resets the scanner to read from a new input stream.
	 * Does not close the old reader.
	 *
	 * All internal variables are reset, the old input stream 
	 * <b>cannot</b> be reused (internal buffer is discarded and lost).
	 * Lexical state is set to <tt>YY_INITIAL</tt>.
	 *
	 * @param reader   the new input stream 
	 */
	public final void yyreset(Reader reader) {
		// 's' has been updated.
		zzBuffer = s.array;
		/*
		 * We replaced the line below with the two below it because zzRefill
		 * no longer "refills" the buffer (since the way we do it, it's always
		 * "full" the first time through, since it points to the segment's
		 * array).  So, we assign zzEndRead here.
		 */
		//zzStartRead = zzEndRead = s.offset;
		zzStartRead = s.offset;
		zzEndRead = zzStartRead + s.count - 1;
		zzCurrentPos = zzMarkedPos = zzPushbackPos = s.offset;
		zzLexicalState = YYINITIAL;
		zzReader = reader;
		zzAtBOL  = true;
		zzAtEOF  = false;
	}




  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MarvelTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public MarvelTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 140) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { addNullToken(); return firstToken;
          }
        case 27: break;
        case 21: 
          { addToken(Token.LITERAL_CHAR);
          }
        case 28: break;
        case 16: 
          { start = zzMarkedPos-2; yybegin(MLC);
          }
        case 29: break;
        case 7: 
          { addToken(Token.WHITESPACE);
          }
        case 30: break;
        case 22: 
          { addToken(Token.ERROR_STRING_DOUBLE);
          }
        case 31: break;
        case 17: 
          { addToken(Token.LITERAL_NUMBER_FLOAT);
          }
        case 32: break;
        case 18: 
          { addToken(Token.RESERVED_WORD);
          }
        case 33: break;
        case 9: 
          { addToken(Token.SEPARATOR);
          }
        case 34: break;
        case 1: 
          { addToken(Token.IDENTIFIER);
          }
        case 35: break;
        case 12: 
          { addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 36: break;
        case 3: 
          { addToken(Token.ERROR_CHAR); addNullToken(); return firstToken;
          }
        case 37: break;
        case 5: 
          { addToken(Token.ERROR_STRING_DOUBLE); addNullToken(); return firstToken;
          }
        case 38: break;
        case 23: 
          { addToken(Token.DATA_TYPE);
          }
        case 39: break;
        case 20: 
          { yybegin(YYINITIAL); addToken(start,zzStartRead+2-1, Token.COMMENT_MULTILINE);
          }
        case 40: break;
        case 14: 
          { addToken(Token.ERROR_CHAR);
          }
        case 41: break;
        case 24: 
          { addToken(Token.LITERAL_BOOLEAN);
          }
        case 42: break;
        case 15: 
          { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
          }
        case 43: break;
        case 26: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_EOL); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_EOL); start = zzMarkedPos;
          }
        case 44: break;
        case 25: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_MULTILINE); start = zzMarkedPos;
          }
        case 45: break;
        case 19: 
          { addToken(Token.RESERVED_WORD_2);
          }
        case 46: break;
        case 13: 
          { addToken(Token.ERROR_NUMBER_FORMAT);
          }
        case 47: break;
        case 6: 
          { start = zzMarkedPos-1; yybegin(EOL_COMMENT);
          }
        case 48: break;
        case 2: 
          { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
          }
        case 49: break;
        case 8: 
          { addToken(Token.OPERATOR);
          }
        case 50: break;
        case 10: 
          { 
          }
        case 51: break;
        case 11: 
          { addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
          }
        case 52: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case EOL_COMMENT: {
              addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
            }
            case 150: break;
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 151: break;
            case MLC: {
              addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
            }
            case 152: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
